### ISSUE TITLE
Create CONTRIBUTING.md and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by hmthomax** [opensecuritycontroller/community#46]
These documents will let the OSC community know the guidelines for contributing to OSC as well as code of conduct/ethics the team and project follow.

**Comment by ychoma** [comment]
@arvindn05 Arvind added code of condact to osc-core will add to other repos

**Comment by ychoma** [comment]
@emanoelxavier please validate after fixed

**Comment by arvindn05** [comment]
@emanoelxavier created code of conduct for all the repos(left out nuage for now). Please validate and close

**Comment by emanoelxavier** [comment]
@arvindn05 please track with an issue on the pan and nuage plugins to have the same.
