### ISSUE TITLE
Links are not set correctly in the Issues Template Document

### ISSUE THREAD

**Issue by ychoma** [opensecuritycontroller/community#66]
### Document Issue

**Document Location**: [blob/master/ISSUE_TEMPLATE.md](https://github.com/opensecuritycontroller/community/blob/master/ISSUE_TEMPLATE.md)

**Document Description**: 
When clicking on the link we are not going to the right location

### Status
- [ ] In Progress

**Comment by hmthomax** [comment]
The document link is supposed to be provided by the user when they fill out the template as described in the comments of the template (just as you have done in this issue). In the [issue template](https://github.com/opensecuritycontroller/community/blob/master/ISSUE_TEMPLATE.md) itself, the link is a placeholder and is not to be used as an actual, working link.

**Comment by arvindn05** [comment]
closing based on comment above
