### ISSUE TITLE
when I build the osc image , I met a problem ,who knows how to solve this problem

### ISSUE THREAD

**Issue by liuxuejiao123** [opensecuritycontroller/community#88]
[exec] [INFO] org.osc.core:osc-service-api ....................... SUCCESS [  9.757 s]
     [exec] [INFO] org.osc.core:osc-rest-server ....................... SUCCESS [ 14.576 s]
     [exec] [INFO] org.osc.core:osc-resolver .......................... SUCCESS [  6.508 s]
     [exec] [INFO] org.osc.core:osc-installer ......................... SUCCESS [  9.835 s]
     [exec] [INFO] org.osc.core:osc-server ............................ SUCCESS [09:34 min]
     [exec] [INFO] org.osc.core:osc-ui-widgetset ...................... SUCCESS [  2.759 s]
     [exec] [INFO] org.osc.core:osc-ui ................................ SUCCESS [01:39 min]
     [exec] [INFO] org.osc.core:osc-uber .............................. SUCCESS [  2.946 s]
     [exec] [INFO] org.osc.core:osc-control ........................... SUCCESS [ 43.153 s]
     [exec] [INFO] org.osc.core:osc-installer-test .................... SUCCESS [ 17.452 s]
     [exec] [INFO] org.osc.core:osc-installer-simple .................. SUCCESS [  4.751 s]
     [exec] [INFO] org.osc.core:osc-export ............................ SUCCESS [ 20.729 s]
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] BUILD SUCCESS
     [exec] [INFO] ------------------------------------------------------------------------
     [exec] [INFO] Total time: 14:01 min
     [exec] [INFO] Finished at: 2017-10-31T12:28:05+08:00
     [exec] [INFO] Final Memory: 127M/1674M
     [exec] [INFO] ------------------------------------------------------------------------

prodVersion:
     [echo] Full Version: 1.0.0-SNAPSHOT-128-gabfa924
     [echo] Version: 1.0.0-SNAPSHOT

ovfOnly:
    [touch] Creating /tmp/build_marker
     [exec] E: /etc/schroot/chroot.d/centos.conf: Unknown chroot type ¡®directory
     [exec] ¡¯
     [exec] Result: 1
   [delete] Deleting: /tmp/build_marker

createBuildDir:
    [mkdir] Created dir: /root/OpenSecurityController/osc-core/Build1.0.0-SNAPSHOT-128-gabfa924

copyServerUpgradeBundle:
     [copy] Copying 1 file to /root/OpenSecurityController/osc-core/Build1.0.0-SNAPSHOT-128-gabfa924

copyPlugins:

checkImagesTocopy:

vmdkImageCopy:

qcow2ImageCopy:

BUILD FAILED
/root/OpenSecurityController/osc-core/build.

xml:124: Warning: Could not find file /root/OpenSecurityController/osc-core/osc-server-bom/OSC_disk-0.qcow2 to copy.

Total time: 14 minutes 4 seconds
root@SZV1000305060:~/OpenSecurityController/osc-core#

**Comment by arvindn05** [comment]
same as #87. closing the duplicate issue.
